# Imagen base con Python 3
FROM python:3.12-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivos necesarios al contenedor
COPY entrega.py .
COPY notas.txt .

# Comando para ejecutar el script
CMD ["python", "entrega.py"]

